/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * cookFood - version 1.0.0
 *
 *
 *
 * OpenAPI version: 3.0.1
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'recipe.get_recipe_id': ['GET', '/recipe/{id}'],
  'recipe.get_recipe_keyword': ['GET', '/recipe/keyword'],
  'recipe.get_recipe_name': ['GET', '/recipe/name'],
  'recipe.get_recipe_list': ['GET', '/recipe/list'],
  'recipe.get_recipe_ingredients': ['GET', '/recipe/ingredients'],
  'review.get_review_recipeid': ['GET', '/review/{recipeId}'],
  'review.post_review': ['POST', '/review'],
  'review.delete_review_id': ['DELETE', '/review/{id}'],
  'ingredient.get_ingredient_name': ['GET', '/ingredient/name'],
  'ingredient.get_ingredient_id': ['GET', '/ingredient/{id}'],
  'ingredient.get_ingredient_description': ['GET', '/ingredient/description'],
  'user.post_user': ['POST', '/user'],
  'user.get_user': ['GET', '/user'],
  'user.put_user': ['PUT', '/user'],
  'recipe.get_recipe_random_count': ['GET', '/recipe/random/{count}']
};
